[general]
import = ["os.toml"]
[env]
TERM = "alacritty"

[window]
title = "Terminal"
dynamic_title = true
decorations_theme_variant = "Dark"
dimensions = { columns = 90, lines = 40 }
option_as_alt = "Both"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 750
blink_timeout = 0

[colors.primary]
background = "#141415"
foreground = "#cdd6cd"

[colors.normal]
black   = "#252530"
red     = "#d8647e"
green   = "#7fa563"
yellow  = "#f3be7c"
blue    = "#6e94b2"
magenta = "#bb9dbd"
cyan    = "#aeaed1"
white   = "#cdcdcd"

[colors.bright]
black   = "#606079"
red     = "#e08398"
green   = "#99b782"
yellow  = "#f5cb96"
blue    = "#8ba9c1"
magenta = "#c9b1ca"
cyan    = "#bebeda"
white   = "#d7d7d7"

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
]

